### ISSUE TITLE
Move Dependencies From MAUS To Kohlrahbi

### ISSUE THREAD

**Issue by hf-krechan** [Hochfrequenz/kohlrahbi#361]
At the moment we have a cyclic dependency between `kohlrahbi` and `MAUS`.

This approach does not follow best practise.
We have a strong coupling between these packages.
But the goal should be a loose coupling.

So we need to move all classes from MAUS which we import in kohlrahbi to kohlrahbi.

## Classes/Functions we need to move

- [x] `EdifactFormat` => https://github.com/Hochfrequenz/efoli/pull/2; https://github.com/Hochfrequenz/mig_ahb_utility_stack/pull/434
- [x] `get_format_of_pruefidentifikator()`=> https://github.com/Hochfrequenz/efoli/pull/2; https://github.com/Hochfrequenz/mig_ahb_utility_stack/pull/434
- [x] `EdifactFormatVersion`=> https://github.com/Hochfrequenz/efoli/pull/2; https://github.com/Hochfrequenz/mig_ahb_utility_stack/pull/434
- [x] `FlatAhbCsvReader`
- [x] `AhbLine`
- [x] `AhbMetaInformation`
- [x] `FlatAnwendungshandbuch`
- [x] `FlatAnwendungshandbuchSchema`

These classes need then to be removed from `MAUS` and import from `kohlrahbi`

**Comment by hf-kklein** [comment]
I'm against moving these 3:
- EdifactFormat
- get_format_of_pruefidentifikator()
- EdifactFormatVersion

this would require LOTS of changed dependencies in LOTS of repos:
https://github.com/search?q=org%3AHochfrequenz+from+maus.edifact+import+EdifactFormat+language%3APython&type=code&l=Python
https://github.com/search?q=org%3AHochfrequenz+from+maus.edifact+import+EdifactFormatVersion+language%3APython&type=code

**Comment by hf-kklein** [comment]
It's important to port not only the model class structures but especially the attrs-based validations.
Without the validations it's only half as useful as it is right now.

**Comment by hf-krechan** [comment]
Alright, than I will copy the mentioned classes and functions to kohlrahbi so that we can remove the maus dependency.
Is this fine?

**Comment by hf-kklein** [comment]
as long as the the 2 enums + 1 function stay in maus, we'll need the maus dependency.
I'm generally happy to get stuff out of maus because it _may_ become obsolete with the new XML based data structures.
But still we need a central place to define the common enums: Format+FormatVersion

Maybe we just create a new repo and package just for that (EdifactFormat, EdifactFormatVersion + helper methods)? Basically all the stuff from the `maus.edifact` module.

We could then also add a dependency of maus to the new repo, and let maus re-export the models as their own. this would minimize side effects during the transition period.

**Comment by hf-krechan** [comment]
So we can close this issue 🎉
